In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr = np.array((1, 3, 2)) #array created by passing tuple
arr

array([1, 3, 2])

In [8]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 8], [3, -7, 2.25, 5], [6, 0, 4, -1]])
arr2 = arr[:2, ::2]
print("first 2 rows and alternate columns(0 and 2):", arr2)
arr3 = arr[[1, 1, 0, 3], [0, 2, 1, 3]]

print("\nElements at indices (1,3), " "(1, 2), (0,1), (3,0):\n", arr3)

first 2 rows and alternate columns(0 and 2): [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1,3), (1, 2), (0,1), (3,0):
 [ 4.  6.  2. -1.]


In [ ]:
#basic array operations
a = np.array([[1,2], [3,4]  ])
b = np.array([[4,3], [2,1]  ])