In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr = np.array((1, 3, 2)) #array created by passing tuple
arr

array([1, 3, 2])

In [6]:
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 8], [3, -7, 2.25, 5], [6, 0, 4, -1]])
arr2 = arr[:2, ::2]
print("first 2 rows and alternate columns(0 and 2):", arr2)
arr3 = arr[[1, 1, 0, 3], [0, 2, 1, 3]]

print("\nElements at indices (1,3), " "(1, 2), (0,1), (3,0):\n", arr3)

first 2 rows and alternate columns(0 and 2): [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1,3), (1, 2), (0,1), (3,0):
 [ 4.  6.  2. -1.]


In [7]:
#basic array operations
a = np.array([[1,2], [3,4]  ])
b = np.array([[4,3], [2,1]  ])

In [8]:
#creating the array
import numpy as np

l = [1, 2, 3, 4, 5]
a = np.array(l)
print(a)

[1 2 3 4 5]


In [9]:
a0 = np.zeros((3, 4))
a1 = np.ones((2, 3))
a2 = np.full((3, 3), 7)
a3 = np.arange(0, 10, 2)
la = np.linspace(0, 1, 5)

print("Array of zeros:\n", a0)
print("\nArray of ones:\n", a1)
print("\nArray filled with 7:\n", a2)
print("\nArray with values from 0 to 10 with step 2:\n", a3)
print("\nArray with 5 values evenly spaced between 0 and 1:\n", la)


Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array with values from 0 to 10 with step 2:
 [0 2 4 6 8]

Array with 5 values evenly spaced between 0 and 1:
 [0.   0.25 0.5  0.75 1.  ]


In [11]:
ar = np.random.rand(3, 3)
an = np.random.randn(3, 3)
ai = np.random.randint(1, 10, size=(2, 3))

print(ar)

print(an)

print(ai)

[[0.32825886 0.65805637 0.13161251]
 [0.4278434  0.42684593 0.72346107]
 [0.13640556 0.97201387 0.79140778]]
[[-0.17677339  0.00750555 -0.61490985]
 [ 1.29055251 -0.411422    0.91718311]
 [-0.27248851 -0.86027618  0.68503919]]
[[8 7 9]
 [6 2 5]]


In [12]:
im = np.eye(3)
da = np.diag([1, 2, 3])
a0 = np.zeros_like(da)
a1 = np.ones_like(da)

print("Identity matrix:\n", im)
print("diagonal matrix:\n", da)
print("zeros matrix:\n", a0)
print("ones matrix:\n", a1)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
zeros matrix:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
ones matrix:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
arr = np.array([10, 20, 30,40, 50])

print(arr[0])

10


In [15]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])
print(matrix[0,1])

6
2


In [19]:
cube = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],

                [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

print(cube[1, 2, 0])

16


In [20]:
import numpy as np 

arr = np.array([0, 1, 2,3, 4, 5,])

print(arr[1:4])

[1 2 3]


In [ ]:
#Doubt
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [22]:
arr = np.array([10, 15 , 20, 25, 30])

print(arr[arr > 20])

[25 30]


In [25]:
arr = np.array([10, 15, 20, 25, 30])
print(arr[(arr > 10) & (arr < 30)])

[15 20 25]


In [26]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


In [27]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])

[1 3 5]


In [28]:
cube = np.random.rand(4, 4, 4)
print(cube[..., 0])

[[0.35793584 0.94022286 0.02910251 0.94233896]
 [0.49200219 0.79844617 0.20515487 0.15927182]
 [0.00178982 0.75099697 0.77876862 0.00609411]
 [0.41295363 0.06093148 0.24555542 0.85048966]]


In [29]:
arr = np.array([1, 2, 3])

print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


In [30]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:3] = 99
print(arr)

[ 1 99 99  4  5]


In [31]:
arr =np.array([[10, 20, 30], [40, 5, 66],[70, 88, 94]])
print("Array:")
print(arr)

res = arr[[0, 2]]
print("Accessed Rows :")
print(res)

Array:
[[10 20 30]
 [40  5 66]
 [70 88 94]]
Accessed Rows :
[[10 20 30]
 [70 88 94]]


In [33]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

r = a.reshape(2, 3)

print(r)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
#resizing Array

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize((3, 2))
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#stacking

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
res = np.stack((a, b), axis=0)
print(res)

[[1 2 3]
 [4 5 6]]


In [ ]:
#splitting

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])
res = np.array_split(arr, 4)
print(res)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#Array Broadcasting

In [38]:
a = np.array([[1,2,3],[4,5,6]])
x = 10
print(a + x)

[[11 12 13]
 [14 15 16]]


In [39]:
arr = np.array([1, 2, 3])
res = arr + 1
print(res)

[2 3 4]


In [40]:
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7,9,11]])
res = a + b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [ ]:
a = np.array([12,24,35,45,60,72])
b = np.array(["Adult","Minor"])
res = np.where(a > 18, b[0], b[1])
print(res)

In [41]:
m = np.array([[1, 2], [3, 4]])
v = np.array([10, 20])
res = m * v
print(res)

[[10 40]
 [30 80]]
